<script setup lang="ts">
import { ref } from 'vue'
import { api, type RegisteredProject } from '../lib/api'
import UiButton from './UiButton.vue'
import UiModal from './UiModal.vue'
const props = defineProps<{ projects: RegisteredProject[] }>()
const emit = defineEmits<{ changed: []; opened: [] }>()
const error = ref(''); const busy = ref(false); const modal = ref<'import'|'adopt'|'relocate'|'remove'|'open'|null>(null); const project = ref<RegisteredProject|null>(null); const root = ref(''); const displayName = ref('')
function show(kind: typeof modal.value, item?: RegisteredProject) { modal.value = kind; project.value = item ?? null; root.value = item?.repository_root ?? ''; displayName.value = ''; error.value = '' }
function close() { if (!busy.value) modal.value = null }
async function submit() { busy.value = true; error.value = ''; try { if (modal.value === 'import') await api.importProject(root.value.trim(), displayName.value.trim() || undefined); if (modal.value === 'adopt') await api.adoptProject(root.value.trim(), displayName.value.trim() || undefined); if (modal.value === 'relocate' && project.value) await api.relocateProject(project.value.id, root.value.trim()); if (modal.value === 'remove' && project.value) await api.removeProject(project.value.id); if (modal.value === 'open' && project.value) { await api.openProject(project.value.id); modal.value = null; emit('opened'); return } modal.value = null; emit('changed') } catch (err: unknown) { error.value = String(err) } finally { busy.value = false } }
</script>
<template>
  <section class="project-picker"><div class="picker-intro"><span class="eyebrow">ORC / PROJECT REGISTRY</span><h2>Choose a project</h2><p>Open a remembered project or import a repository. No project state is created until you choose an action.</p><div class="lead-actions"><UiButton variant="primary" :loading="busy" @click="show('import')">IMPORT PROJECT</UiButton><UiButton :loading="busy" @click="show('adopt')">INITIALIZE / ADOPT GIT REPOSITORY</UiButton></div></div><div v-if="error" class="notice">{{ error }}</div><div v-if="!props.projects.length" class="panel empty">NO REMEMBERED PROJECTS. IMPORT OR ADOPT A REPOSITORY TO BEGIN.</div><div v-for="item in props.projects" :key="item.id" class="panel project-card"><div><h3>{{ item.display_name }}</h3><p class="project-path">{{ item.repository_root }}</p><span class="pill" :class="item.status.toLowerCase()">{{ item.status }}</span><p v-if="item.status !== 'Available'" class="project-error">This project cannot be opened at its remembered location. Relocate it or remove it from the registry.</p></div><div class="lead-actions"><UiButton variant="primary" :disabled="!item.available" @click="show('open', item)">OPEN</UiButton><UiButton v-if="item.status === 'Missing' || item.status === 'TemporarilyUnavailable'" @click="show('relocate', item)">RELOCATE</UiButton><UiButton @click="show('remove', item)">REMOVE</UiButton></div></div><UiModal :open="modal !== null" :title="modal === 'remove' ? 'Remove remembered project' : modal === 'open' ? 'Switch active project' : modal === 'adopt' ? 'Initialize or adopt Git repository' : modal === 'relocate' ? 'Relocate project' : 'Import project'" @close="close"><p v-if="modal === 'remove'">Remove {{ project?.display_name }} from remembered projects? Repository data will not be deleted.</p><p v-else-if="modal === 'open'">Open {{ project?.display_name }}? This switches the active project.</p><form v-else @submit.prevent="submit"><label>Repository path<input v-model="root" required autofocus /></label><label v-if="modal === 'import' || modal === 'adopt'">Display name (optional)<input v-model="displayName" /></label></form><div v-if="error" class="notice">{{ error }}</div><div class="lead-actions"><UiButton @click="close">CANCEL</UiButton><UiButton variant="primary" :loading="busy" @click="submit">{{ modal === 'remove' ? 'REMOVE' : modal === 'open' ? 'OPEN PROJECT' : modal === 'adopt' ? 'INITIALIZE / ADOPT' : modal === 'relocate' ? 'VERIFY AND RELOCATE' : 'IMPORT' }}</UiButton></div></UiModal></section>
</template>
